version: '2.4'

x-app: &app
  volumes:
    - ./:/workspace

services:
  onnx-tf:
    <<: *app
    build:
      context: dockerfiles/onnx-tf

  timm-onnx:
    <<: *app
    build:
      context: dockerfiles/timm-onnx
