version: '2.4'

x-env: &env
  TENSORBOARD_PORT: ${TENSORBOARD_PORT:?}
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN}
  KAGGLE_USERNAME: &KAGGLE_USERNAME ${KAGGLE_USERNAME}
  KAGGLE_KEY: &KAGGLE_KEY ${KAGGLE_KEY}
  

x-app: &app
  volumes:
    - ./:/workspace


services:
  onnx-tf:
    <<: *app
    build:
      context: dockerfiles/onnx-tf
    command: onnx-tf

  timm-onnx:
    <<: *app
    build:
      context: dockerfiles/timm-onnx
    command: timm-onnix



